amazon:
  base_url: "https://www.amazon.com/s?k="
  auth_content:
    User-Agent: ""

  headers:
    Accept-Encoding: "gzip, deflate"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    DNT: "1"
    Connection: "close"
    Upgrade-Insecure-Requests: "1"

  User_Agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.1.2 Safari/602.3.12"

  categories:
    - "electronics"
    - "books"

ebay:
  base_url: "https://www.ebay.com/b/"
  auth_content:
    User-Agent: ""

  headers:
    Accept-Encoding: "gzip, deflate"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    DNT: "1"
    Connection: "close"
    Upgrade-Insecure-Requests: "1"

  User_Agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.1.2 Safari/602.3.12"

  categories:
    - "electronics"
    - "books"

database:
  collections:
    amazon: "amazon_products"
    ebay: "ebay_products"

scraper:
  sleep_interval: 1
